// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoneyManagement.DbContexts;

#nullable disable

namespace MoneyManagement.Migrations
{
    [DbContext(typeof(FinanceContext))]
    [Migration("20240726123617_addSeed")]
    partial class addSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("MoneyManagement.Entities.Account", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfCreation")
                        .HasColumnType("TEXT");

                    b.Property<int>("InterestInterval")
                        .HasColumnType("INTEGER");

                    b.Property<double>("InterestRate")
                        .HasColumnType("REAL");

                    b.Property<int>("InvestmentDuration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Overdraft")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("MoneyManagement.Entities.Category", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Name = "Art Supplies"
                        },
                        new
                        {
                            Name = "Games"
                        },
                        new
                        {
                            Name = "Books"
                        },
                        new
                        {
                            Name = "Clothing"
                        },
                        new
                        {
                            Name = "Hygiene"
                        },
                        new
                        {
                            Name = "Other Fees"
                        },
                        new
                        {
                            Name = "Groceries"
                        },
                        new
                        {
                            Name = "Household"
                        },
                        new
                        {
                            Name = "Insurance"
                        },
                        new
                        {
                            Name = "Other Hobbies"
                        },
                        new
                        {
                            Name = "Health"
                        },
                        new
                        {
                            Name = "Stream and Tv"
                        },
                        new
                        {
                            Name = "Phone"
                        },
                        new
                        {
                            Name = "House"
                        },
                        new
                        {
                            Name = "Taxes"
                        },
                        new
                        {
                            Name = "Car & Fuel"
                        },
                        new
                        {
                            Name = "Salary"
                        },
                        new
                        {
                            Name = "Present"
                        },
                        new
                        {
                            Name = "Cashback"
                        },
                        new
                        {
                            Name = "Transer"
                        });
                });

            modelBuilder.Entity("MoneyManagement.Entities.Transaction", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("FromAccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToAccountId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("MoneyManagement.Entities.Transaction", b =>
                {
                    b.HasOne("MoneyManagement.Entities.Account", null)
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MoneyManagement.Entities.Account", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
